fix piupartslib imports
During the port to python3 piupartslib was changed to no longer
auto-import some of its submodules. Import the required submodules
directly where now needed.

Fixes:

Traceback (most recent call last):
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-report", line 1910, in <module>
    main()
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-report", line 1849, in main
    section = Section(section_name, master_directory, doc_root, packagedb_cache=packagedb_cache)
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-report", line 827, in __init__
    self._load_package_database(section, master_directory)
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-report", line 859, in _load_package_database
    db = piupartslib.packagesdb.PackagesDB(prefix=sectiondir)
AttributeError: module 'piupartslib' has no attribute 'packagesdb'

Signed-off-by: Holger Levsen <holger@layer-acht.org>