piupartslib/packagesdb: encode contents for os.write
Fixes:

  File "/srv/piuparts.debian.org/lib/python3/dist-packages/piupartslib/packagesdb.py", line 260, in create
    if os.write(fd, contents) != len(contents):
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Holger Levsen <holger@layer-acht.org>