piupartslib/packagesdb: concatenate only lists
While one set of dict_keys() was already wrapped in a list() during the
initial porting work, the second one was still missing. Fixes:

  File "/srv/piuparts.debian.org/lib/python3/dist-packages/piupartslib/packagesdb.py", line 818, in get_best_package_state
    for state in self._good_states + list(self._propagate_waiting_state.keys()) + self._propagate_error_state.keys():
TypeError: can only concatenate list (not "dict_keys") to list

Signed-off-by: Holger Levsen <holger@layer-acht.org>