post_du_exceptions: buster: remove empty unowned /etc/dbus-1/{system.d/,}
systemd no longer ships /etc/dbus-1/system.d/* in buster, but dpkg does
not clean up the now empty unowned directories after the upgrade from
stretch to buster

cleanup will happen if another package ships /etc/dbus-1/system.d/*
in buster and gets purged in buster, causing discrepancies with the
reference chroot:

  ERROR: FAIL: After purging files have disappeared:
    /etc/dbus-1/	 owned by: dbus
    /etc/dbus-1/system.d/	 owned by: dbus

Signed-off-by: Andreas Beckmann <anbe@debian.org>
Signed-off-by: Holger Levsen <holger@layer-acht.org>