piuparts-master-backend: handle BrokenPipeError
No need to crash with a stacktrace when the slave is gone and the pipe
to it is broken. Just log this and exit 1.

Fixes:

Traceback (most recent call last):
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-master-backend", line 433, in <module>
    main()
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-master-backend", line 423, in main
    m = Master(sys.stdin, sys.stdout)
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-master-backend", line 154, in __init__
    self._writeline("hello")
  File "/srv/piuparts.debian.org/share/piuparts/piuparts-master-backend", line 111, in _writeline
    self._output.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

Signed-off-by: Holger Levsen <holger@layer-acht.org>