piupartslib/dependencyparser: mynext() does not take args
Arguments were accidentally introduced when porting the code to python3.
Remove them again. Fixes:

  File "/srv/piuparts.debian.org/lib/python3/dist-packages/piupartslib/dependencyparser.py", line 266, in _parse_version_dependency
    self._cursor.mynext(self._cursor)
TypeError: mynext() takes 1 positional argument but 2 were given

Signed-off-by: Holger Levsen <holger@layer-acht.org>